version: "3"
services:
  app:
    build: .
    container_name: fastapi_scaffold
    command: >-
      sh -c "
        alembic upgrade head ;\
        uvicorn server:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8003:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app:rw
    networks:
      - app_network

  postgres:
    image: postgres:14-alpine
    container_name: fastapi_scaffold_db
    ports:
      - "5434:5432"
    restart: "no"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=homestead
      - POSTGRES_USER=homestead
      - POSTGRES_PASSWORD=secret
    networks:
      - app_network

  redis:
    image: redis:6-alpine
    container_name: fastapi_scaffold_cache
    ports:
      - "6379:6379"
    volumes:
      - cache_data:/data
    networks:
      - app_network

volumes:
  db_data:
    driver: "local"
  cache_data:
    driver: "local"

networks:
  app_network:
    driver: "bridge"
